# Generated by Django 4.2.26 on 2025-12-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=20, unique=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('CE', 'Cedula de Extranjeria'), ('TI', 'Tarjeta de Identidad'), ('PA', 'Pasaporte')], default='CC', max_length=3)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('nivel_educativo', models.CharField(choices=[('TEC', 'Tecnico'), ('TGL', 'Tecnologo'), ('DOC', 'Doctorado'), ('PRE', 'Pregrado'), ('ESP', 'Especializacion'), ('MAE', 'Maestria')], default='MAE', max_length=3)),
                ('especialidad', models.CharField(max_length=100)),
                ('años_experiencia', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_vinculacion', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
