# Generated by Django 4.2.26 on 2025-12-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructores', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instructores',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='nivel_educativo',
            field=models.CharField(choices=[('TEC', 'Tecnico'), ('TGL', 'Tecnólogo'), ('PRE', 'Pregrado'), ('ESP', 'Especialización'), ('MAE', 'Maestría'), ('DOC', 'Doctorado')], default='MAE', max_length=3),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PA', 'Pasaporte')], default='CC', max_length=3),
        ),
    ]
